name: Terraform to Azure (CD)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticating Azure to allow Terraform
      run: az login --service-principal -u "1936dabf-4102-4051-857c-ae84a978b142" --tenant "b174724f-0430-44cc-893f-10943c2a8463"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 3.0.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
