name: Terraform to Azure (CD)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticating Azure to allow Terraform
      run: az login --service-principal -u "ffa31409-48c5-4a26-9bea-136143b8650e" -p "f4a0c39e-f522-48ac-8591-d44723c72491" --tenant "b174724f-0430-44cc-893f-10943c2a8463"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 3.0.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
